[package]
name = "non"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.51", features = ["derive"] }
nom = "8.0.0"
serde = { version = "1.0.228", features = ["derive", "rc"] }
thiserror = "2.0.17"
